### ISSUE TITLE
Community (https://www.scicommons.org/mycommunity) Join Requests not accepting when more than 1 user sent for join request

### ISSUE THREAD

**Issue by rajubugude** [m2b3/SciCommons-backend#5]
This I first encountered while running on local setup.
<img width="1236" alt="Screenshot 2024-03-14 at 9 54 33 PM" src="https://github.com/m2b3/SciCommons-backend/assets/88735632/8dffa8cd-c2ae-4080-90f9-f3a290312e16">

Here is the error that when more than 1 user requests to join a particular community . When I tried the same process in website same error repeats(can be seen in console).
 
<img width="1792" alt="Screenshot 2024-03-14 at 10 04 52 PM" src="https://github.com/m2b3/SciCommons-backend/assets/88735632/ded577ae-3f35-4057-b23a-ebb89f5ebbc8">

**Comment by JyothiSwaroopReddy07** [comment]
issue is resolved
